### ISSUE TITLE
Reported hostname is empty

### ISSUE THREAD

**Issue by RossBoylan** [HenrikBengtsson/ucsf-vpn#19]
There is a function to extract the hostname out of the connection information.  But I don't think there's anything to extract.  The connection info comes from the following command, whose output appears below:
```
$ curl --silent https://ipinfo.io/json
{
  "ip": "128.218.192.91",
  "city": "San Francisco",
  "region": "California",
  "country": "US",
  "loc": "37.7758,-122.4130",
  "postal": "94103",
  "phone": "415",
  "org": "AS5653 University of California San Francisco"
}
```

So `public_hostname`, which greps for `"hostname"` is not going to find anything.

**Comment by HenrikBengtsson** [comment]
To clarify this issue: The problem here is that the we get the output:
```
Connected to the UCSF network [ (128.218.42.91)]
```
The reported hostname is empty, which results in that empty space in front of the IP number.

It turns out that 'hostname' is only available sometimes.  It seems like it is not available while on the UCSF network (as above), but when otherwise it might be, e.g.
```
Not connected to the UCSF network [123-123-204-91.example.org (123.123.204.91)]
```

**Comment by HenrikBengtsson** [comment]
I've updated this in the develop branch to report as:
```
Connected to the UCSF network [ip=128.218.43.53, hostname='', org='AS5653 University of California San Francisco']
```
and
```
RESULT: Not connected to the UCSF network [ip=157.131.204.163, hostname='example.org', org='AS12345 Example Organization']
```
